# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1377LfYbz8O_lf3LWASkh25sVXsE6W1ko

PARTE 1: Clase Color
"""

class Color:
    def __init__(self, color: str):
        self.__color = None
        self.color = color

    @property
    def color(self):
        return self.__color

    @color.setter
    def color(self, value):
        if not isinstance(value, str) or value.strip() == "":
            raise ValueError("El color debe ser un texto válido.")
        self.__color = value

    def __str__(self):
        return f"Color: {self.__color}"

"""PARTE 2: Clase FiguraGeometrica"""

class FiguraGeometrica:
    def __init__(self, alto: float, ancho: float):
        self.__alto = None
        self.__ancho = None
        self.alto = alto
        self.ancho = ancho

    @property
    def alto(self):
        return self.__alto

    @alto.setter
    def alto(self, value):
        if value <= 0:
            raise ValueError("El alto debe ser mayor a 0.")
        self.__alto = value

    @property
    def ancho(self):
        return self.__ancho

    @ancho.setter
    def ancho(self, value):
        if value <= 0:
            raise ValueError("El ancho debe ser mayor a 0.")
        self.__ancho = value

    def __str__(self):
        return f"Alto: {self.__alto}, Ancho: {self.__ancho}"

"""PARTE 3: Clase Cuadrado (Herencia + sobrescritura)"""

class Cuadrado(FiguraGeometrica, Color):
    def __init__(self, lado, color):
        FiguraGeometrica.__init__(self, lado, lado)
        Color.__init__(self, color)

    def area(self):
        return self.alto * self.ancho

    def perimetro(self):
        return 4 * self.alto

    def __str__(self):
        return f"[Cuadrado] {FiguraGeometrica.__str__(self)} - {Color.__str__(self)}"

"""PARTE 4: Clase Rectangulo"""

class Rectangulo(FiguraGeometrica, Color):
    def __init__(self, alto, ancho, color):
        FiguraGeometrica.__init__(self, alto, ancho)
        Color.__init__(self, color)

    def area(self):
        return self.alto * self.ancho

    def perimetro(self):
        return 2 * (self.alto + self.ancho)

    def __str__(self):
        return f"[Rectángulo] {FiguraGeometrica.__str__(self)} - {Color.__str__(self)}"

"""PARTE 5: Clase Circunferencia"""

import math


class Circunferencia(Color):
    def __init__(self, radio, color):
        super().__init__(color)
        self.__radio = None
        self.radio = radio

    @property
    def radio(self):
        return self.__radio

    @radio.setter
    def radio(self, value):
        if value <= 0:
            raise ValueError("El radio debe ser mayor a 0.")
        self.__radio = value

    def area(self):
        return math.pi * self.__radio ** 2

    def perimetro(self):
        return 2 * math.pi * self.__radio

    def __str__(self):
        return f"[Circunferencia] Radio: {self.__radio} - {Color.__str__(self)}"

"""PARTE 6: Ejecución_Evidencias"""

if __name__ == "__main__":
    print("=== PRUEBAS ===\n")

    try:
        # Cuadrado
        c = Cuadrado(5, "Rojo")
        print(c)
        print("Área:", c.area())
        print("Perímetro:", c.perimetro(), "\n")

        # Rectángulo
        r = Rectangulo(4, 6, "Azul")
        print(r)
        print("Área:", r.area())
        print("Perímetro:", r.perimetro(), "\n")

        # Circunferencia
        cir = Circunferencia(3, "Verde")
        print(cir)
        print("Área:", round(cir.area(), 2))
        print("Perímetro:", round(cir.perimetro(), 2), "\n")

        # Validación (error)
        print("Prueba de error:")
        error = Cuadrado(-2, "Negro")

    except ValueError as e:
        print("Error detectado:", e)